### ISSUE TITLE
AS Giraffe and up support

### ISSUE THREAD

**Issue by Vrachno** [itkacher/OkHttpProfiler#39]
First of all, hope you are safe with everything going on in your country.

Android Studio went through a massive overhaul in the latest versions, and it seems that the plugin has stopped working again. Are there any plans for an update in the near future?

**Comment by gektor650** [comment]
@Vrachno Thank you for your compassion. I am fine, unlike most of my country :( 

The plugin has been fixed. 

https://plugins.jetbrains.com/plugin/11249-okhttp-profiler/versions/stable/373734

It will take several dates to complete the JetBrains review to install it manually (you can download the zip file from the link above).

**Comment by Vrachno** [comment]
Works perfectly on Giraffe, thanks! Still not working on Hedgehog Canary but I guess you can revisit this when it's on stable channel.

You will prevail. Slava Ukraini!
